<?php
// $Id$

/**
 * @file
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function jrst_custom_ctools_plugin_directory($module, $plugin) {
  if ($module == 'feeds_tamper') {
    return 'plugins';
  }
}

function jrst_custom_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'user_profile_form':
    case 'user_register':
      $form['account']['mail']['#description'] = t('A valid e-mail address. All e-mails will be sent to this address');
      break;
    case 'group_node_form':
      $form['taxonomy']['#group'] = FALSE;
      break;

  }
}

function jrst_custom_link_alter(&$links, $node, $comment = NULL) {
  $one = 1;
  if ($node->type == 'blog') {
    unset($links['blog_usernames_blog']);
  }
}